import {
  AuthAccessReadScope,
  AuthOrchestrationOperateScope,
  AuthOrchestrationReadScope,
  AuthReviewWriteScope,
  AuthTerminalOperateScope,
  AuthVmOperateScope,
  ORCHESTRATION_WS_METHODS,
  type AuthEnvironmentScope,
  WS_METHODS,
  WsRpcGroup,
} from "@t3tools/contracts";
import type * as RpcGroup from "effect/unstable/rpc/RpcGroup";

type WsRpcMethod = RpcGroup.Rpcs<typeof WsRpcGroup>["_tag"];

/**
 * Keep authorization coverage coupled to the RPC group itself. Adding an RPC to
 * `WsRpcGroup` without choosing a scope is a type error instead of a production
 * runtime failure.
 */
export const RPC_REQUIRED_SCOPES = {
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: AuthOrchestrationOperateScope,
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.searchThreads]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeShell]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getArchivedShellSnapshot]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeThread]: AuthOrchestrationReadScope,
  [WS_METHODS.serverProbe]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRefreshProviders]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverStartProviderAccountSwitch]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetProviderAccountSwitch]: AuthOrchestrationReadScope,
  [WS_METHODS.serverOpenProviderAccountSwitchAuthLink]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverSubmitProviderAccountSwitchCode]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverCancelProviderAccountSwitch]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateProvider]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServer]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpsertKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverRemoveKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetSettings]: AuthOrchestrationReadScope,
  [WS_METHODS.serverUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverDiscoverSourceControl]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetTraceDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessResourceHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetResourceTelemetryHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRetryResourceTelemetry]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverSignalProcess]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverReportClientActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.serverReportHostPowerState]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetBackgroundPolicy]: AuthOrchestrationReadScope,
  [WS_METHODS.sourceControlLookupRepository]: AuthOrchestrationReadScope,
  [WS_METHODS.sourceControlCloneRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlPublishRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectsListEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsReadFile]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchContents]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsWriteFile]: AuthOrchestrationOperateScope,
  [WS_METHODS.shellOpenInEditor]: AuthOrchestrationOperateScope,
  [WS_METHODS.filesystemBrowse]: AuthOrchestrationReadScope,
  [WS_METHODS.assetsCreateUrl]: AuthOrchestrationReadScope,
  [WS_METHODS.threadArtifactsList]: AuthOrchestrationReadScope,
  [WS_METHODS.threadArtifactsGet]: AuthOrchestrationReadScope,
  [WS_METHODS.threadArtifactsArchive]: AuthOrchestrationOperateScope,
  [WS_METHODS.threadArtifactsRestore]: AuthOrchestrationOperateScope,
  [WS_METHODS.threadArtifactsDelete]: AuthOrchestrationOperateScope,
  [WS_METHODS.threadArtifactsSubscribe]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeVcsStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeResourceTelemetry]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsRefreshStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsPull]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitRunStackedAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitResolvePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitPreparePullRequestThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsListRefs]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsCreateWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsRemoveWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsCreateRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsSwitchRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsInit]: AuthOrchestrationOperateScope,
  [WS_METHODS.reviewGetDiffPreview]: AuthReviewWriteScope,
  [WS_METHODS.terminalOpen]: AuthTerminalOperateScope,
  [WS_METHODS.terminalAttach]: AuthTerminalOperateScope,
  [WS_METHODS.terminalList]: AuthTerminalOperateScope,
  [WS_METHODS.terminalRead]: AuthTerminalOperateScope,
  [WS_METHODS.terminalWrite]: AuthTerminalOperateScope,
  [WS_METHODS.terminalResize]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClear]: AuthTerminalOperateScope,
  [WS_METHODS.terminalRestart]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClose]: AuthTerminalOperateScope,
  [WS_METHODS.terminalGetLayout]: AuthTerminalOperateScope,
  [WS_METHODS.terminalSetLayout]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalEvents]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalMetadata]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalLayouts]: AuthTerminalOperateScope,
  [WS_METHODS.previewOpen]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewNavigate]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewResize]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewRefresh]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewClose]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewList]: AuthOrchestrationReadScope,
  [WS_METHODS.previewReportStatus]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationConnect]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationFocusHost]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostConnect]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostPublishFrame]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostPublishVideoChunk]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostEnd]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlHostReportStatus]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlRequestAccess]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlWatch]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlSendInput]: AuthOrchestrationOperateScope,
  [WS_METHODS.remoteControlCancel]: AuthOrchestrationOperateScope,
  [WS_METHODS.vmAgentCreate]: AuthVmOperateScope,
  [WS_METHODS.vmAgentBuilderOpen]: AuthVmOperateScope,
  [WS_METHODS.vmAgentDelete]: AuthVmOperateScope,
  [WS_METHODS.vmAgentStart]: AuthVmOperateScope,
  [WS_METHODS.vmAgentStop]: AuthVmOperateScope,
  [WS_METHODS.vmAgentSetControlMode]: AuthVmOperateScope,
  [WS_METHODS.vmAgentSendInput]: AuthVmOperateScope,
  [WS_METHODS.vmAgentSubscribe]: AuthVmOperateScope,
  [WS_METHODS.vmAgentSubscribeScreen]: AuthVmOperateScope,
  [WS_METHODS.vmAgentWorkspaceSubscribe]: AuthVmOperateScope,
  [WS_METHODS.vmAgentTaskCreate]: AuthVmOperateScope,
  [WS_METHODS.vmAgentTaskUpdate]: AuthVmOperateScope,
  [WS_METHODS.vmAgentTaskDelete]: AuthVmOperateScope,
  [WS_METHODS.vmAgentTaskRunNow]: AuthVmOperateScope,
  [WS_METHODS.vmAgentTaskGeneratePrompt]: AuthVmOperateScope,
  [WS_METHODS.vmAgentNotificationMarkRead]: AuthVmOperateScope,
  [WS_METHODS.vmAgentNotificationPreferencesUpdate]: AuthVmOperateScope,
  [WS_METHODS.vmAgentCollaborationSubscribe]: AuthVmOperateScope,
  [WS_METHODS.vmAgentCollaborationGet]: AuthVmOperateScope,
  [WS_METHODS.vmAgentCollaborationSendMessage]: AuthVmOperateScope,
  [WS_METHODS.vmAgentCollaborationCancel]: AuthVmOperateScope,
  [WS_METHODS.subscribePreviewEvents]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeDiscoveredLocalServers]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerLifecycle]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeAuthAccess]: AuthAccessReadScope,
  [WS_METHODS.subscribeBackgroundPolicy]: AuthOrchestrationReadScope,
} as const satisfies Readonly<Record<WsRpcMethod, AuthEnvironmentScope>>;

export function requiredScopeForRpcMethod(method: string): AuthEnvironmentScope {
  if (!Object.hasOwn(RPC_REQUIRED_SCOPES, method)) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  const requiredScope = RPC_REQUIRED_SCOPES[method as WsRpcMethod];
  if (requiredScope === undefined) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  return requiredScope;
}
