import type { McpInvocationScope } from "./McpInvocationContext.ts";

import { T3_BROWSER_CONTROL_POLICY } from "../browserControlPolicy.ts";

export const TERMINAL_AGENT_PROVIDER_INSTANCE_ID = "solla-terminal-agent";

export const SOLLA_MCP_SERVER_INSTRUCTIONS = `You are connected to Solla Code's credential-bound t3-code MCP server. Use its artifact tool to publish durable thread-owned previews that remain available on remote devices, thread_collaboration to inspect or coordinate parent and sibling chats, agent_collaboration when this credential belongs to a custom agent or delegated worker, its history tools for persisted transcripts, its terminal tools for live panes, and its preview tools for attached browser surfaces. ${T3_BROWSER_CONTROL_POLICY} Treat preview_open lifecycle results as authoritative: resolve selection-required by reusing an offered tab ID or explicitly requesting a new tab, reuse tabs reported as created during that browsing task, and close those created tabs with preview_close when finished; never close a reused tab merely as cleanup. Before a consequential external action such as sending email or messages, publishing, purchasing, or changing an account, call request_action_approval with the exact destination and content, and act only after it returns approved. A human-gated request returns pending immediately so it cannot block other T3 tools: do not retry it, create a duplicate blocker or notification, or continue the gated branch. End the turn; in Agent mode emit AGENT_STOP. Solla starts a fresh turn carrying the approval or requested corrections. Ordinary Agent-mode turns auto-approve that request, but delegated turns always require explicit human approval. The server is injected in memory and is not expected to appear in repository or user MCP configuration. Call the provider-qualified tool names exposed by your client and fetch live state instead of assuming prompt context is current.`;

export const SOLLA_TERMINAL_MCP_SERVER_INSTRUCTIONS = `You are running as an agent launched from Solla Code's integrated terminal and are attached to the Solla thread that owns this terminal. The credential-bound t3-code MCP server is injected by Solla; it is not expected to appear in repository or user MCP configuration. Use its artifact tool to publish durable thread-owned previews that remain available on remote devices, thread_collaboration to inspect or coordinate parent and sibling chats, agent_collaboration when this credential belongs to a custom agent or delegated worker, its history tools for persisted transcripts, its terminal tools for live panes, and its preview tools for attached browser surfaces. ${T3_BROWSER_CONTROL_POLICY} Treat preview_open lifecycle results as authoritative: resolve selection-required by reusing an offered tab ID or explicitly requesting a new tab, reuse tabs reported as created during that browsing task, and close those created tabs with preview_close when finished; never close a reused tab merely as cleanup. Before a consequential external action such as sending email or messages, publishing, purchasing, or changing an account, call request_action_approval with the exact destination and content, and act only after it returns approved. A human-gated request returns pending immediately so it cannot block other T3 tools: do not retry it, create a duplicate blocker or notification, or continue the gated branch. End the turn; in Agent mode emit AGENT_STOP. Solla starts a fresh turn carrying the approval or requested corrections. Ordinary Agent-mode turns auto-approve that request, but delegated turns always require explicit human approval. Call the provider-qualified tool names exposed by your client and fetch live state instead of assuming prompt context is current.`;

export function mcpServerInstructionsForScope(scope: McpInvocationScope): string {
  return scope.providerInstanceId === TERMINAL_AGENT_PROVIDER_INSTANCE_ID
    ? SOLLA_TERMINAL_MCP_SERVER_INSTRUCTIONS
    : SOLLA_MCP_SERVER_INSTRUCTIONS;
}
