/**
 * xterm only emits mouse/focus report sequences as input when it believes the
 * running program enabled tracking — but replayed bytes from a shared PTY can
 * leave tracking latched on after that program is gone, and then every cursor
 * move types reports like `35;48;1M` into the shell. Local mode resets close
 * most of that window, but the summary they depend on races attach, so the
 * write path additionally strips report payloads whenever no subprocess is in
 * the foreground: a bare shell never wants them.
 */
const TERMINAL_MOUSE_REPORT_PATTERN =
  // SGR (1006) reports, legacy X10/VT200 (`ESC [ M` + 3 bytes), URXVT (1015)
  // numeric reports, and focus-tracking (1004) in/out events.
  // eslint-disable-next-line no-control-regex
  /\x1b\[<\d+;\d+;\d+[Mm]|\x1b\[M[\s\S]{3}|\x1b\[\d+;\d+;\d+M|\x1b\[[IO]/g;

export function stripTerminalMouseReports(data: string): string {
  return data.replace(TERMINAL_MOUSE_REPORT_PATTERN, "");
}

// Tracking mode 1003 emits a report for every pointer move, even when no
// button is held. Those reports are not actionable terminal input, and two
// attached clients can otherwise saturate the renderer and WebSocket with
// them. Preserve clicks, releases, drags, wheel events, and focus reports.
// eslint-disable-next-line no-control-regex
const TERMINAL_SGR_MOUSE_REPORT_PATTERN = /\x1b\[<(\d+);\d+;\d+[Mm]/g;
// eslint-disable-next-line no-control-regex
const TERMINAL_X10_MOUSE_REPORT_PATTERN = /\x1b\[M([\s\S])([\s\S])([\s\S])/g;
// eslint-disable-next-line no-control-regex
const TERMINAL_URXVT_MOUSE_REPORT_PATTERN = /\x1b\[(\d+);\d+;\d+M/g;

function isUnbuttonedMouseMotion(buttonCode: number): boolean {
  return (buttonCode & 32) !== 0 && (buttonCode & 3) === 3;
}

export function stripTerminalUnbuttonedMouseMotionReports(data: string): string {
  return data
    .replace(TERMINAL_SGR_MOUSE_REPORT_PATTERN, (report, rawButtonCode: string) =>
      isUnbuttonedMouseMotion(Number(rawButtonCode)) ? "" : report,
    )
    .replace(TERMINAL_X10_MOUSE_REPORT_PATTERN, (report, rawButtonCode: string) => {
      const buttonCode = rawButtonCode.codePointAt(0);
      return buttonCode !== undefined && isUnbuttonedMouseMotion(buttonCode - 32) ? "" : report;
    })
    .replace(TERMINAL_URXVT_MOUSE_REPORT_PATTERN, (report, rawButtonCode: string) =>
      isUnbuttonedMouseMotion(Number(rawButtonCode)) ? "" : report,
    );
}

/**
 * Replies xterm sends when it re-parses a *query* that is sitting in replayed
 * scrollback.
 *
 * Same root cause as the latched mouse tracking above, one step further on. A
 * TUI asks the terminal for its palette with `OSC 4 ; n ; ? BEL`, and that
 * query is part of the PTY output every attaching client replays. Re-parsing
 * history makes xterm answer it again - politely, correctly, and far too late:
 * the program that asked got its answer long ago, so the reply lands in
 * whatever is reading the line now and is typed into it. On a phone, where
 * unfocusing the pane re-lays-out and replays the buffer, that is the wall of
 * `]4;1;rgb:f0f0/7171/7878\` the person sees appear in their prompt - and
 * then gets answered by the agent, because as far as the CLI is concerned the
 * user typed it.
 *
 * These are only ever *replies*, never something a person can type, so they
 * are safe to drop from the input path during a replay. A live program that
 * genuinely wants the palette asks again on its next repaint and gets its
 * answer, because the suppression lasts only as long as the replay write.
 */
const TERMINAL_STATUS_REPORT_REPLY_PATTERN =
  // OSC 4 (indexed palette) and OSC 10/11/12 (fg/bg/cursor) colour reports,
  // ST- or BEL-terminated; primary/secondary device attributes; the cursor
  // position report; and DECRPM mode reports.
  // eslint-disable-next-line no-control-regex
  /\x1b\](?:4;\d+|1[012]);rgb:[0-9a-fA-F/]+(?:\x1b\\|\x07)|\x1b\[[?>]?[\d;]*c|\x1b\[\d+;\d+R|\x1b\[\?\d+;\d+\$y/g;

/**
 * Drop terminal-generated status replies from an input payload.
 *
 * Applied only while replayed bytes are being parsed. Outside that window a
 * reply is an answer to a question the foreground program actually just
 * asked, and swallowing it would hang whatever is waiting for it.
 */
export function stripTerminalStatusReportReplies(data: string): string {
  return data.replace(TERMINAL_STATUS_REPORT_REPLY_PATTERN, "");
}

/** Only the shared grid owner answers live queries; replies never claim input ownership. */
export function routeTerminalInput(
  data: string,
  input: {
    replaying: boolean;
    ownsGeometry: boolean;
  },
): { data: string; claimsGeometry: boolean } {
  const userData = stripTerminalStatusReportReplies(data);
  return {
    data: input.replaying || !input.ownsGeometry ? userData : data,
    // Focus-in/out is generated by the renderer too, not a typed command.
    // eslint-disable-next-line no-control-regex
    claimsGeometry: userData.replace(/\x1b\[[IO]/g, "").length > 0,
  };
}
