import type { VmAgentIcon } from "@t3tools/contracts";
import {
  AnchorIcon,
  AtomIcon,
  BikeIcon,
  BookOpenIcon,
  BotIcon,
  BrainIcon,
  BriefcaseIcon,
  BugIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  ChartLineIcon,
  ClapperboardIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  DnaIcon,
  DumbbellIcon,
  EyeIcon,
  FeatherIcon,
  FilmIcon,
  FlameIcon,
  FlaskConicalIcon,
  Gamepad2Icon,
  GemIcon,
  GlobeIcon,
  GraduationCapIcon,
  HammerIcon,
  HeadphonesIcon,
  HeartPulseIcon,
  HouseIcon,
  ImageIcon,
  KeyRoundIcon,
  LandmarkIcon,
  LanguagesIcon,
  LeafIcon,
  LightbulbIcon,
  MailIcon,
  MapIcon,
  MegaphoneIcon,
  MicIcon,
  MonitorIcon,
  MusicIcon,
  NewspaperIcon,
  PackageIcon,
  PaletteIcon,
  PawPrintIcon,
  PencilRulerIcon,
  PhoneIcon,
  PiggyBankIcon,
  PlaneIcon,
  RadioIcon,
  RocketIcon,
  ScaleIcon,
  ScissorsIcon,
  SearchIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SparklesIcon,
  StethoscopeIcon,
  SunIcon,
  TelescopeIcon,
  TerminalIcon,
  TrophyIcon,
  TruckIcon,
  UmbrellaIcon,
  UserRoundIcon,
  Wand2Icon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from "lucide-react";

import { resolveAgentGlyphKey, type AgentGlyphKey } from "./agentGlyphKey";

/** Every persisted icon id the contract allows, bound to its outlined glyph. */
const PERSISTED_ICONS: Record<VmAgentIcon, LucideIcon> = {
  anchor: AnchorIcon,
  atom: AtomIcon,
  bike: BikeIcon,
  "book-open": BookOpenIcon,
  bot: BotIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  bug: BugIcon,
  calculator: CalculatorIcon,
  calendar: CalendarIcon,
  camera: CameraIcon,
  car: CarIcon,
  "chart-line": ChartLineIcon,
  clapperboard: ClapperboardIcon,
  cloud: CloudIcon,
  code: CodeIcon,
  coffee: CoffeeIcon,
  compass: CompassIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  dna: DnaIcon,
  dumbbell: DumbbellIcon,
  eye: EyeIcon,
  feather: FeatherIcon,
  film: FilmIcon,
  flame: FlameIcon,
  "flask-conical": FlaskConicalIcon,
  "gamepad-2": Gamepad2Icon,
  gem: GemIcon,
  globe: GlobeIcon,
  "graduation-cap": GraduationCapIcon,
  hammer: HammerIcon,
  headphones: HeadphonesIcon,
  "heart-pulse": HeartPulseIcon,
  house: HouseIcon,
  image: ImageIcon,
  "key-round": KeyRoundIcon,
  landmark: LandmarkIcon,
  languages: LanguagesIcon,
  leaf: LeafIcon,
  lightbulb: LightbulbIcon,
  mail: MailIcon,
  map: MapIcon,
  megaphone: MegaphoneIcon,
  mic: MicIcon,
  monitor: MonitorIcon,
  music: MusicIcon,
  newspaper: NewspaperIcon,
  package: PackageIcon,
  palette: PaletteIcon,
  "paw-print": PawPrintIcon,
  "pencil-ruler": PencilRulerIcon,
  phone: PhoneIcon,
  "piggy-bank": PiggyBankIcon,
  plane: PlaneIcon,
  radio: RadioIcon,
  rocket: RocketIcon,
  scale: ScaleIcon,
  scissors: ScissorsIcon,
  search: SearchIcon,
  shield: ShieldIcon,
  "shopping-cart": ShoppingCartIcon,
  sparkles: SparklesIcon,
  stethoscope: StethoscopeIcon,
  sun: SunIcon,
  telescope: TelescopeIcon,
  terminal: TerminalIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  umbrella: UmbrellaIcon,
  "user-round": UserRoundIcon,
  "wand-2": Wand2Icon,
  wrench: WrenchIcon,
  zap: ZapIcon,
};

/** Name-derived stand-ins for agents that have not chosen an icon yet. */
const FALLBACK_ICONS: Record<AgentGlyphKey, LucideIcon> = {
  paw: PawPrintIcon,
  heart: HeartPulseIcon,
  user: UserRoundIcon,
  pencil: PencilRulerIcon,
  globe: GlobeIcon,
  monitor: MonitorIcon,
  bot: BotIcon,
  cpu: CpuIcon,
  rocket: RocketIcon,
  compass: CompassIcon,
  flask: FlaskConicalIcon,
  wrench: WrenchIcon,
};

/**
 * The agent's outlined glyph. The persisted icon (chosen by the AI that
 * created the agent, or by its own first run) wins; until one exists the
 * glyph is derived from the name so rows never show a generic robot.
 *
 * Renders a bare svg so sidebar rows can style it like any other leading
 * icon (`[&>svg]` rules expect a direct child).
 */
export function AgentGlyph({
  name,
  icon,
  className,
}: {
  name: string;
  icon?: VmAgentIcon | null | undefined;
  className?: string;
}) {
  const Icon = icon ? PERSISTED_ICONS[icon] : FALLBACK_ICONS[resolveAgentGlyphKey(name)];
  return <Icon aria-hidden className={className} />;
}
